apiVersion: v1
kind: ConfigMap
metadata:
  name: llm-runner-config
  namespace: llm-systems
  labels:
    app: llm-runner-router
    component: config
  annotations:
    reloader.stakater.com/match: "true"
data:
  # Application Configuration
  routing-strategy: "balanced"
  max-memory: "4096"
  cache-enabled: "true"
  log-level: "info"
  
  # Performance Configuration
  max-concurrent-requests: "100"
  request-timeout: "30000"
  model-load-timeout: "300000"
  cache-ttl: "3600"
  
  # Model Configuration
  auto-download-models: "false"
  model-cache-size: "10Gi"
  default-model-format: "gguf"
  
  # Security Configuration
  enable-cors: "true"
  rate-limit-requests: "100"
  rate-limit-window: "60"
  
  # Monitoring Configuration
  enable-metrics: "true"
  metrics-port: "9090"
  health-check-interval: "30"
  
  # WebSocket Configuration
  ws-heartbeat-interval: "30000"
  ws-max-connections: "1000"
  ws-compression: "true"
  
  # Engine Configuration
  preferred-engine: "node-native"
  fallback-engines: "wasm,simple"
  enable-gpu-acceleration: "false"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: llm-runner-nginx-config
  namespace: llm-systems
  labels:
    app: llm-runner-router
    component: nginx-config
data:
  nginx.conf: |
    upstream llm_backend {
        least_conn;
        server llm-runner-router:3006 max_fails=3 fail_timeout=30s;
    }
    
    upstream llm_websocket {
        ip_hash;
        server llm-runner-router:8080 max_fails=3 fail_timeout=30s;
    }
    
    map $http_upgrade $connection_upgrade {
        default upgrade;
        '' close;
    }
    
    server {
        listen 80;
        server_name _;
        
        # Security headers
        add_header X-Frame-Options "SAMEORIGIN" always;
        add_header X-Content-Type-Options "nosniff" always;
        add_header X-XSS-Protection "1; mode=block" always;
        
        # Rate limiting
        limit_req_zone $binary_remote_addr zone=api:10m rate=10r/s;
        limit_req_zone $binary_remote_addr zone=ws:10m rate=5r/s;
        
        # API endpoints
        location /api/ {
            limit_req zone=api burst=20 nodelay;
            proxy_pass http://llm_backend;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_connect_timeout 60s;
            proxy_send_timeout 60s;
            proxy_read_timeout 60s;
        }
        
        # WebSocket endpoints
        location /ws {
            limit_req zone=ws burst=10 nodelay;
            proxy_pass http://llm_websocket;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection $connection_upgrade;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_read_timeout 3600s;
            proxy_send_timeout 3600s;
        }
        
        # Static files
        location / {
            proxy_pass http://llm_backend;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
        
        # Health check
        location /health {
            access_log off;
            proxy_pass http://llm_backend/api/health;
        }
    }

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: llm-runner-env-config
  namespace: llm-systems
  labels:
    app: llm-runner-router
    component: env-config
data:
  .env: |
    # LLM Runner Router Environment Configuration
    NODE_ENV=production
    PORT=3006
    WS_PORT=8080
    
    # Routing Configuration
    ROUTING_STRATEGY=balanced
    MAX_MEMORY=4096
    CACHE_ENABLED=true
    
    # Performance Configuration
    MAX_CONCURRENT_REQUESTS=100
    REQUEST_TIMEOUT=30000
    MODEL_LOAD_TIMEOUT=300000
    
    # Logging Configuration
    LOG_LEVEL=info
    LOG_FORMAT=json
    
    # Security Configuration
    ENABLE_CORS=true
    RATE_LIMIT_REQUESTS=100
    RATE_LIMIT_WINDOW=60
    
    # Model Configuration
    AUTO_DOWNLOAD_MODELS=false
    MODEL_CACHE_SIZE=10737418240
    DEFAULT_MODEL_FORMAT=gguf
    
    # WebSocket Configuration
    WS_HEARTBEAT_INTERVAL=30000
    WS_MAX_CONNECTIONS=1000
    WS_COMPRESSION=true