apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "llm-runner-router.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "llm-runner-router.labels" . | nindent 4 }}
  annotations:
    deployment.kubernetes.io/revision: "1"
spec:
  replicas: {{ .Values.deployment.replicaCount }}
  strategy:
    type: {{ .Values.deployment.strategy.type }}
    {{- if eq .Values.deployment.strategy.type "RollingUpdate" }}
    rollingUpdate:
      maxSurge: {{ .Values.deployment.strategy.rollingUpdate.maxSurge }}
      maxUnavailable: {{ .Values.deployment.strategy.rollingUpdate.maxUnavailable }}
    {{- end }}
  selector:
    matchLabels:
      {{- include "llm-runner-router.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "llm-runner-router.selectorLabels" . | nindent 8 }}
        {{- with .Values.deployment.pod.labels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      annotations:
        {{- if .Values.monitoring.enabled }}
        prometheus.io/scrape: "true"
        prometheus.io/port: "3006"
        prometheus.io/path: "/metrics"
        {{- end }}
        {{- with .Values.deployment.pod.annotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.image.pullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "llm-runner-router.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.deployment.pod.securityContext | nindent 8 }}
      containers:
      - name: {{ .Values.deployment.pod.container.name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        {{- range .Values.deployment.pod.container.ports }}
        - name: {{ .name }}
          containerPort: {{ .containerPort }}
          protocol: {{ .protocol }}
        {{- end }}
        env:
        - name: NODE_ENV
          value: {{ .Values.config.nodeEnv | quote }}
        - name: PORT
          value: {{ .Values.config.port | quote }}
        - name: WS_PORT
          value: {{ .Values.config.wsPort | quote }}
        - name: ROUTING_STRATEGY
          value: {{ .Values.config.routingStrategy | quote }}
        - name: MAX_MEMORY
          value: {{ .Values.config.maxMemory | quote }}
        - name: CACHE_ENABLED
          value: {{ .Values.config.cacheEnabled | quote }}
        - name: LOG_LEVEL
          value: {{ .Values.config.logLevel | quote }}
        {{- if .Values.secrets.create }}
        - name: HUGGINGFACE_TOKEN
          valueFrom:
            secretKeyRef:
              name: {{ include "llm-runner-router.fullname" . }}-secrets
              key: huggingface-token
              optional: true
        - name: API_KEY
          valueFrom:
            secretKeyRef:
              name: {{ include "llm-runner-router.fullname" . }}-secrets
              key: api-key
              optional: true
        {{- end }}
        resources:
          {{- toYaml .Values.deployment.pod.container.resources | nindent 10 }}
        volumeMounts:
        {{- if .Values.persistence.enabled }}
        - name: model-cache
          mountPath: /app/models/cache
        - name: logs-volume
          mountPath: /app/logs
        - name: shared-cache
          mountPath: /app/cache
        {{- end }}
        - name: temp-volume
          mountPath: /tmp
        livenessProbe:
          {{- toYaml .Values.deployment.pod.container.livenessProbe | nindent 10 }}
        readinessProbe:
          {{- toYaml .Values.deployment.pod.container.readinessProbe | nindent 10 }}
        startupProbe:
          {{- toYaml .Values.deployment.pod.container.startupProbe | nindent 10 }}
        securityContext:
          {{- toYaml .Values.deployment.pod.container.securityContext | nindent 10 }}
      volumes:
      {{- if .Values.persistence.enabled }}
      - name: model-cache
        persistentVolumeClaim:
          claimName: {{ include "llm-runner-router.fullname" . }}-model-cache
      - name: logs-volume
        persistentVolumeClaim:
          claimName: {{ include "llm-runner-router.fullname" . }}-logs
      - name: shared-cache
        persistentVolumeClaim:
          claimName: {{ include "llm-runner-router.fullname" . }}-shared-cache
      {{- end }}
      - name: temp-volume
        emptyDir:
          sizeLimit: 500Mi
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      terminationGracePeriodSeconds: 60
      dnsPolicy: ClusterFirst
      restartPolicy: Always