{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "llm-runner-router.fullname" . }}-netpol
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "llm-runner-router.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "llm-runner-router.selectorLabels" . | nindent 6 }}
  policyTypes:
  {{- if .Values.networkPolicy.ingress.enabled }}
  - Ingress
  {{- end }}
  {{- if .Values.networkPolicy.egress.enabled }}
  - Egress
  {{- end }}
  {{- if .Values.networkPolicy.ingress.enabled }}
  ingress:
  # Allow traffic from ingress controllers
  - from:
    - namespaceSelector:
        matchLabels:
          name: ingress-nginx
    - namespaceSelector:
        matchLabels:
          name: kube-system
    ports:
    - protocol: TCP
      port: 3006
    - protocol: TCP
      port: 8080
  # Allow traffic from monitoring systems
  - from:
    - namespaceSelector:
        matchLabels:
          name: monitoring
    ports:
    - protocol: TCP
      port: 3006
    - protocol: TCP
      port: 9090
  # Allow traffic from other pods in the same namespace
  - from:
    - namespaceSelector:
        matchLabels:
          name: {{ .Release.Namespace }}
    ports:
    - protocol: TCP
      port: 3006
    - protocol: TCP
      port: 8080
  # Allow traffic from load balancer health checks
  - from: []
    ports:
    - protocol: TCP
      port: 3006
  {{- with .Values.networkPolicy.ingress.from }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
  {{- end }}
  {{- if .Values.networkPolicy.egress.enabled }}
  egress:
  # Allow DNS resolution
  - to: []
    ports:
    - protocol: UDP
      port: 53
    - protocol: TCP
      port: 53
  # Allow HTTPS to external APIs
  - to: []
    ports:
    - protocol: TCP
      port: 443
  # Allow HTTP to external APIs
  - to: []
    ports:
    - protocol: TCP
      port: 80
  # Allow access to Kubernetes API server
  - to:
    - namespaceSelector:
        matchLabels:
          name: kube-system
    ports:
    - protocol: TCP
      port: 443
  # Allow access to internal services
  - to:
    - namespaceSelector:
        matchLabels:
          name: {{ .Release.Namespace }}
  # Allow access to monitoring and logging
  - to:
    - namespaceSelector:
        matchLabels:
          name: monitoring
    ports:
    - protocol: TCP
      port: 9090
    - protocol: TCP
      port: 3100
    - protocol: TCP
      port: 9200
  {{- with .Values.networkPolicy.egress.to }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
  {{- end }}
{{- end }}