{{- if .Values.secrets.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "llm-runner-router.secretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "llm-runner-router.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.secrets.data.huggingfaceToken }}
  huggingface-token: {{ .Values.secrets.data.huggingfaceToken | b64enc }}
  {{- else }}
  huggingface-token: {{ "REPLACE_WITH_HUGGINGFACE_TOKEN" | b64enc }}
  {{- end }}
  
  {{- if .Values.secrets.data.apiKey }}
  api-key: {{ .Values.secrets.data.apiKey | b64enc }}
  {{- else }}
  api-key: {{ "REPLACE_WITH_API_KEY" | b64enc }}
  {{- end }}
  
  {{- if .Values.secrets.data.jwtSecret }}
  jwt-secret: {{ .Values.secrets.data.jwtSecret | b64enc }}
  {{- else }}
  jwt-secret: {{ randAlphaNum 32 | b64enc }}
  {{- end }}
  
  {{- if .Values.secrets.data.dbPassword }}
  db-password: {{ .Values.secrets.data.dbPassword | b64enc }}
  {{- else }}
  db-password: {{ "REPLACE_WITH_DB_PASSWORD" | b64enc }}
  {{- end }}
  
  {{- if .Values.secrets.data.redisPassword }}
  redis-password: {{ .Values.secrets.data.redisPassword | b64enc }}
  {{- else }}
  redis-password: {{ "REPLACE_WITH_REDIS_PASSWORD" | b64enc }}
  {{- end }}
  
  {{- if .Values.secrets.data.openaiApiKey }}
  openai-api-key: {{ .Values.secrets.data.openaiApiKey | b64enc }}
  {{- else }}
  openai-api-key: {{ "REPLACE_WITH_OPENAI_KEY" | b64enc }}
  {{- end }}
  
  {{- if .Values.secrets.data.anthropicApiKey }}
  anthropic-api-key: {{ .Values.secrets.data.anthropicApiKey | b64enc }}
  {{- else }}
  anthropic-api-key: {{ "REPLACE_WITH_ANTHROPIC_KEY" | b64enc }}
  {{- end }}
{{- end }}