apiVersion: v1
kind: Service
metadata:
  name: {{ include "llm-runner-router.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "llm-runner-router.labels" . | nindent 4 }}
  annotations:
    {{- with .Values.service.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
  {{- range .Values.service.ports }}
  - name: {{ .name }}
    port: {{ .port }}
    targetPort: {{ .targetPort }}
    protocol: {{ .protocol }}
    {{- if and (eq $.Values.service.type "NodePort") .nodePort }}
    nodePort: {{ .nodePort }}
    {{- end }}
  {{- end }}
  selector:
    {{- include "llm-runner-router.selectorLabels" . | nindent 4 }}
  {{- if .Values.service.sessionAffinity }}
  sessionAffinity: {{ .Values.service.sessionAffinity }}
  {{- if .Values.service.sessionAffinityConfig }}
  sessionAffinityConfig:
    {{- toYaml .Values.service.sessionAffinityConfig | nindent 4 }}
  {{- end }}
  {{- end }}
  {{- with .Values.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
    {{- toYaml . | nindent 4 }}
  {{- end }}

---
# Internal service for cluster communication
apiVersion: v1
kind: Service
metadata:
  name: {{ include "llm-runner-router.fullname" . }}-internal
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "llm-runner-router.labels" . | nindent 4 }}
    access: internal
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 3006
    targetPort: 3006
    protocol: TCP
  - name: websocket
    port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    {{- include "llm-runner-router.selectorLabels" . | nindent 4 }}

---
# Headless service for StatefulSet-like behavior
apiVersion: v1
kind: Service
metadata:
  name: {{ include "llm-runner-router.fullname" . }}-headless
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "llm-runner-router.labels" . | nindent 4 }}
    access: headless
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - name: http
    port: 3006
    targetPort: 3006
    protocol: TCP
  - name: websocket
    port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    {{- include "llm-runner-router.selectorLabels" . | nindent 4 }}
  publishNotReadyAddresses: false